import json
import os

# --- Configuration ---
# Paths to the Foundry artifacts (adjust if your contract names differ)
ORIGINAL_ARTIFACT = "out/Original.sol/Original.json"
OPTIMIZED_ARTIFACT = "out/Optimized.sol/Optimized.json"
OUTPUT_FILE = "test/AutoGeneratedTest.t.sol"

# --- Templates ---
HEADER_TEMPLATE = """// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;
import "halmos-cheatcodes/SymTest.sol";
import "forge-std/Test.sol";
import {Original} from "../src/Original.sol";
import {Optimized} from "../src/Optimized.sol";

contract AutoGeneratedTest is SymTest, Test {
    Original original;
    Optimized optimized;

    function setUp() public {
        original = new Original();
        optimized = new Optimized();
    }
"""

TEST_FUNCTION_TEMPLATE = """
    function check_equivalence_{func_name}({args_def}) public {{
        // 1. Constraints (Heuristics for loops)
        {constraints}

        // 2. Run Original
        (bool s1, bytes memory r1) = address(original).call(
            abi.encodeWithSelector(original.{func_name}.selector, {arg_names})
        );

        // 3. Run Optimized
        (bool s2, bytes memory r2) = address(optimized).call(
            abi.encodeWithSelector(optimized.{func_name}.selector, {arg_names})
        );

        // 4. Prove Equivalence
        assert(s1 == s2); // Revert status must match
        if (s1) {{
            assert(keccak256(r1) == keccak256(r2)); // Return values must match
        }}
    }}
"""

FOOTER_TEMPLATE = "\n}"

def generate_harness():
    # 1. Load the ABI
    try:
        with open(ORIGINAL_ARTIFACT, 'r') as f:
            data = json.load(f)
            abi = data['abi']
    except FileNotFoundError:
        print(f"Error: Could not find {ORIGINAL_ARTIFACT}. Did you run 'forge build'?")
        return

    test_functions_code = ""
    generated_count = 0

    # 2. Iterate through functions
    for item in abi:
        if item['type'] == 'function' and item['stateMutability'] in ['pure', 'view', 'nonpayable', 'payable']:
            func_name = item['name']
            inputs = item['inputs']
            
            # Construct argument strings: "uint256 n", "address user"
            args_def_list = []
            arg_names_list = []
            constraints_code = ""

            for i, inp in enumerate(inputs):
                arg_name = inp['name'] if inp['name'] else f"arg{i}"
                arg_type = inp['type']
                
                args_def_list.append(f"{arg_type} {arg_name}")
                arg_names_list.append(arg_name)

                # HEURISTIC: Constrain integers to prevent infinite loop timeouts in Halmos
                # This is a crucial "Smart" feature for your paper
                if "int" in arg_type: 
                    constraints_code += f"vm.assume({arg_name} < 100); "

            # Format the template
            test_functions_code += TEST_FUNCTION_TEMPLATE.format(
                func_name=func_name,
                args_def=", ".join(args_def_list),
                arg_names=", ".join(arg_names_list),
                constraints=constraints_code
            )
            generated_count += 1

    # 3. Write the file
    full_source = HEADER_TEMPLATE + test_functions_code + FOOTER_TEMPLATE
    
    with open(OUTPUT_FILE, "w") as f:
        f.write(full_source)
    
    print(f"✅ Success! Generated {generated_count} proofs in {OUTPUT_FILE}")

if __name__ == "__main__":
    generate_harness()