#!/usr/bin/env python3
"""
Print counterexample in a readable format
"""

import sys
import re

# Counterexample from Halmos output
amount_hex = "0x18"
amount_decimal = int(amount_hex, 16)
cap = 20

print("=" * 70)
print("COUNTEREXAMPLE: CappedDeposits Equivalence Failure")
print("=" * 70)
print()
print("Test Function: check_equivalence_deposit(uint256 amount)")
print()
print("Input Values:")
print(f"  amount = {amount_hex} (hex)")
print(f"  amount = {amount_decimal} (decimal)")
print(f"  cap    = {cap} (from constructor: new CappedDeposits(20))")
print()
print("=" * 70)
print("EXECUTION BEHAVIOR")
print("=" * 70)
print()
print("Original Contract (CappedDeposits):")
print("  Code:")
print("    uint256 newBalance = deposits[msg.sender] + amount;")
print(f"    require(newBalance <= cap, \"cap exceeded\");")
print()
print(f"  Execution:")
print(f"    newBalance = 0 + {amount_decimal} = {amount_decimal}")
print(f"    Check: {amount_decimal} <= {cap}? → FALSE")
print(f"    Result: ❌ REVERTS with error \"cap exceeded\"")
print()
print("Optimized Contract (CappedDepositsOpt):")
print("  Code:")
print("    unchecked {")
print("        deposits[msg.sender] += amount;")
print("    }")
print()
print(f"  Execution:")
print(f"    deposits[msg.sender] += {amount_decimal}")
print(f"    Result: ✅ SUCCEEDS (no cap check)")
print()
print("=" * 70)
print("EQUIVALENCE CHECK RESULT")
print("=" * 70)
print()
print("The equivalence test checks:")
print("  assert(success1 == success2);")
print()
print("With amount = 24:")
print("  success1 (Original)  = false (reverted)")
print("  success2 (Optimized) = true  (succeeded)")
print()
print("  assert(false == true) → ❌ FAILS")
print()
print("=" * 70)
print("BUG SUMMARY")
print("=" * 70)
print()
print("🐛 BUG DETECTED: The optimized contract violates the cap constraint!")
print()
print("The optimization removed the cap check to save gas, but this")
print("allows deposits that exceed the maximum allowed amount.")
print()
print("Impact:")
print(f"  - Cap is set to: {cap}")
print(f"  - Deposit of {amount_decimal} is allowed (should be rejected)")
print(f"  - This breaks the security invariant of the contract")
print()
print("=" * 70)

